### ISSUE TITLE
ITEM DATABASE STRUCTURE

### ISSUE THREAD

**Issue by renzadic** [rathena/FluxCP#271] opened 2020-12-07 07:29 UTC
How are we doing i noticed that there is only one comment on the issue at hand so i wanted to post to make it confirmed
by another patron.

Using the newest revision of rAthena with flux users cannot view the item database do to a structure error. Below are the errors which need to be fixed asap if possible. Currently having someone look into it to see if they can fix but needs to be addressed for users using the newest rAthena.

[2020-12-07 03:18:50] [SQLSTATE=42S22] Err 1054: Unknown column 'name_japanese' in 'field list'
[2020-12-07 05:58:11] [SQLSTATE=42S22] Err 1054: Unknown column 'equip_locations' in 'where clause'

**Comment by AthenaStudioInc** [comment] 2020-12-17 06:40
rAthena update all itemdb.sql

**Comment by codetyper** [comment] 2020-12-19 12:33
> rAthena update all itemdb.sql

How it can be fixed?

**Comment by Ninjininja** [comment] 2021-01-25 04:07
> > rAthena update all itemdb.sql
> 
> How it can be fixed?

You gotta import the right version of these into your database:

https://github.com/rathena/rathena/tree/master/sql-files/compatibility

Then you go into **modules\item** (relative to the root) of FluxCP and look for the file called **index.php**

Once in there you change which database it's looking at, to the new "compat" views. So in my case, because I'm Renewal, I went to the following line:

    **if($server->isRenewal) {
        $fromTables = array("{$server->charMapDatabase}.item_db_re", "{$server->charMapDatabase}.item_db2_re");
    } else {
        $fromTables = array("{$server->charMapDatabase}.item_db", "{$server->charMapDatabase}.item_db2");
    }**


And then I altered that entry to read the following. Everything worked again after doing that:


    **if($server->isRenewal) {
        $fromTables = array("{$server->charMapDatabase}.item_db_re_compat", "{$server->charMapDatabase}.item_db2_re_compat");
    } else {
        $fromTables = array("{$server->charMapDatabase}.item_db", "{$server->charMapDatabase}.item_db2");
    }**

**Comment by reunite-ro** [comment] 2021-02-24 12:53
For now, rAthena also already update their mobdb to YML.

**Comment by Lemongrass3110** [comment] 2021-02-26 23:51
Duplicate of #270

**Closed by Lemongrass3110** 2021-02-26 23:51 UTC
